Add extra convenience features to Snowflake
nuclearace/SwiftDiscord pull request #24
Opened 2017-07-05 05:35 UTC by tellowkrinkle

Some convenient features from the Sword project
Hopefully in the future, our conformance to RawRepresentable with UInt64 will get us an auto-implemented Comparable and Hashable, but for now it only gets us Equatable

2017-07-05 18:17 UTC, nuclearace requested changes

2017-07-05 18:17 UTC, nuclearace commented on Sources/SwiftDiscord/DiscordSnowflakeID.swift
> +    public var id: UInt64 { return rawValue }
No need for this. These change haven't been released yet.

2017-07-05 18:17 UTC, nuclearace commented on Sources/SwiftDiscord/DiscordSnowflakeID.swift
> +extension Snowflake {
Is this really needed? Is there a legit reason you would need this info?

2017-07-05 20:55 UTC, tellowkrinkle commented on Sources/SwiftDiscord/DiscordSnowflakeID.swift
> +extension Snowflake {
I can't think of any uses for the three `Int` values, but the Snowflake <-> Timestamp are pretty useful.  Should I remove `workerId`, `processId`, and `numberInProcess`?

2017-07-06 16:50 UTC, nuclearace approved these changes

2017-07-06 16:50 UTC, merged

2017-07-06 16:51 UTC, nuclearace commented on Sources/SwiftDiscord/DiscordSnowflakeID.swift
> +extension Snowflake {
Nah it's fine. Maybe someone will find that info interesting.