Easier embeds
nuclearace/SwiftDiscord pull request #31
Opened 2017-08-09 06:14 UTC by tellowkrinkle

Embeds have a lot of fields that come from many different places and I often find myself wanting to initialize them one at a time instead of all-at-once.  It's also not nearly as dangerous to have large amounts of `var` declarations in a swift struct as it is in a swift class or some other languages, since structs are always passed by copy to other functions, and a `let struct = Struct()` will have all its fields be immutable anyways.

Because of this, I would like to make all user-initializeable fields in a DiscordEmbed be mutable so users can initialize their structs piece by piece.

This PR also includes these smaller changes:
- Title and Description fields aren't actually required in an embed, so those are now optional.
- Discord didn't seem to care previously previously, but it seems like a good idea to entirely leave out `nil` fields from the jsonified forms of embeds (instead of encoding them as `key:null`), so that is now done.
- Added a new test for making sure jsonification and de-jsonification of embeds is working
- Made said test pass by fixing these issues:
    - An issue where the DiscordEmbed initializer used `provider` instead of `thumbnail` as the dictionary key for the thumbnail
    - An issue where the DiscordEmbed initializer used `iconUrl` instead of `icon_url` as the dictionary key for the icon URL
    - An optional URL whose init from JSON defaulted it to localhost instead of nil
    - Renamed `proxyUrl` to `proxyIconUrl` to match with Discord's name.  This isn't that important (since users can't add this field to a message) but we might as well make sure it makes the round trip properly.
- Fixed an issue where the message sending system didn't properly send a message that contained a main message, an embed, and an attachment.
- Made `DiscordEmbed.Image.url` a `URL` instead of a `String`
- Made `DiscordMessage.mentionRoles` a `[RoleID]` instead of a `[String]`
- Replaced a few stray tabs with spaces

2017-08-09 10:25 UTC, nuclearace requested changes
Looks good overall, I have no real strong argument against making these fields var, since you can still choose to use `let` and init all the fields at once if you so choose.

2017-08-09 10:25 UTC, nuclearace commented on Sources/SwiftDiscord/Audit/DiscordAuditLogEntry.swift
> -    case memberBanAdd =	22
Thanks, this was some weird copy-paste that was going on with AppCode, I guess I missed this one.

2017-08-09 10:25 UTC, nuclearace commented on Sources/SwiftDiscord/Channel/DiscordMessage.swift
> +        else {
Else goes on the same line please.

2017-08-09 10:25 UTC, nuclearace commented on Sources/SwiftDiscord/Channel/DiscordMessage.swift
> +        internal init(name: String, iconURL: URL?, url: URL?, proxyURL: URL?) {
I don't think internal is really needed here? iirc you only need to specify a lower visibility if it's a protocol extension.

2017-08-09 10:25 UTC, nuclearace commented on Sources/SwiftDiscord/Channel/DiscordMessage.swift
> +        public let proxyIconUrl: URL?
Thanks.

2017-08-09 10:25 UTC, nuclearace commented on Sources/SwiftDiscord/Channel/DiscordMessage.swift
> +        internal init(text: String?, iconURL: URL?, proxyURL: URL?) {
Might as well name it proxyIconURL to be consistent with the field name.

2017-08-09 10:25 UTC, nuclearace commented on Sources/SwiftDiscord/Channel/DiscordMessage.swift
> +        public var url: URL
Thanks, I was getting lazy.

2017-08-09 10:25 UTC, nuclearace commented on Sources/SwiftDiscord/DiscordJSON.swift
> +            guard shouldIncludeNilsInJSON || (value as? Emptyable)?.isEmpty != true else {
Just an fyi, I prefer to do `optionalBool ?? false` if it's an if statement, but since this is a guard I think this is good.

2017-08-09 10:25 UTC, nuclearace commented on Sources/SwiftDiscord/DiscordJSON.swift
> +extension Optional : Emptyable {
Can just be a fileprivate extension right?

2017-08-09 23:35 UTC, tellowkrinkle commented on Sources/SwiftDiscord/DiscordJSON.swift
> +extension Optional : Emptyable {
I wish: `'fileprivate' modifier cannot be used with extensions that declare protocol conformances`
Maybe it'll happen in Swift 5

2017-08-09 23:36 UTC, tellowkrinkle commented on Sources/SwiftDiscord/Channel/DiscordMessage.swift
> +        internal init(text: String?, iconURL: URL?, proxyURL: URL?) {
Yep, was having too much fun with the fact that Xcode 9 finally got refactoring and forgot to change the other variables named the same thing :)

2017-08-09 23:50 UTC, nuclearace commented on Sources/SwiftDiscord/DiscordJSON.swift
> +extension Optional : Emptyable {
Right.

2017-08-10 13:23 UTC, nuclearace approved these changes

2017-08-10 13:24 UTC, merged